name: Pipeline
on:
  push:
    branches: [ dev ]
env:
  APPLICATION_NAME: startupapp

jobs:
  
  submit_training_job:
    runs-on: ubuntu-latest
    name: Deploy-TrainingPipeline
    steps:
    - uses: actions/checkout@v3
    - name: Fire SageMaker
      id: sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
        AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
      working-directory: ./src
      run: |
        pip install --no-cache-dir --upgrade awscli boto3 sagemaker joblib s3fs fsspec 
        python scripts/training_pipeline.py 

  submit_inference_job:
    runs-on: ubuntu-latest
    name: Deploy-InferencePipeline
    steps:
    - uses: actions/checkout@v3
    - name: Fire SageMaker
      id: sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
        # AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
      working-directory: ./src
      run: |
        pip install --no-cache-dir --upgrade awscli boto3 sagemaker joblib s3fs fsspec xgboost
        python scripts/inference_pipeline.py 